In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('Country_data.csv')

In [37]:
dataset

Country   Age   Salary Purchased
0   france  44.0  72000.0        No
1    spain  27.0  48000.0       Yes
2  germany  30.0  54000.0        No
3    spain  38.0  61000.0        No
4  germany  40.0      NaN       Yes
5   france  35.0  58000.0       Yes
6    spain   NaN  52000.0        No
7   france  48.0  79000.0       Yes
8  germany  50.0  63000.0        No
9   france  37.0  67000.0       Yes

In [4]:
x=dataset[['Country','Age','Salary']].values

In [5]:
x

array([['france', 44.0, 72000.0],
       ['spain', 27.0, 48000.0],
       ['germany', 30.0, 54000.0],
       ['spain', 38.0, 61000.0],
       ['germany', 40.0, nan],
       ['france', 35.0, 58000.0],
       ['spain', nan, 52000.0],
       ['france', 48.0, 79000.0],
       ['germany', 50.0, 63000.0],
       ['france', 37.0, 67000.0]], dtype=object)

In [6]:
y = dataset[['Purchased']].values

In [7]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [8]:
#missing values replace using SimpleImputer
from sklearn.impute import SimpleImputer

In [9]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [10]:
imputer = imputer.fit(x[:,1:3])

In [11]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [12]:
x

array([['france', 44.0, 72000.0],
       ['spain', 27.0, 48000.0],
       ['germany', 30.0, 54000.0],
       ['spain', 38.0, 61000.0],
       ['germany', 40.0, 61555.555555555555],
       ['france', 35.0, 58000.0],
       ['spain', 38.77777777777778, 52000.0],
       ['france', 48.0, 79000.0],
       ['germany', 50.0, 63000.0],
       ['france', 37.0, 67000.0]], dtype=object)

In [13]:
#label encoding
from sklearn.preprocessing import LabelEncoder

In [14]:
label_encoder_x = LabelEncoder()

In [15]:
x[:,0] = label_encoder_x.fit_transform(x[:,0])

In [16]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 61555.555555555555],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 63000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [17]:
#Dummy encoding
from sklearn.preprocessing import OneHotEncoder

In [18]:
onehotencoder = OneHotEncoder()

In [19]:
x = onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [20]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [21]:
#label encoding Y data
labelencoder_y = LabelEncoder()

In [22]:
y = labelencoder_y.fit_transform(y)

C:\PYTHON 3.10.1\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [24]:
# split train data and test data(80%,20%)
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [26]:
x_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [27]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [28]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [29]:
y_test

array([0, 0])

In [30]:
#Feature scaling
from sklearn.preprocessing import StandardScaler

In [31]:
sc_x = StandardScaler()

In [32]:
x_train = sc_x.fit_transform(x_train)

In [33]:
x_test = sc_x.transform(x_test)

In [34]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [35]:
x_test

array([[-1.        ,  2.64575131, -0.77459667],
       [-1.        ,  2.64575131, -0.77459667]])